config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :users do
    resources :followers, only: :index
    resources :followings, only: :index
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get  'signup' => 'users#new'
  delete 'logout' => 'sessions#destroy'

  namespace :admin do
    root 'dashbroads#home'
    resources :categories
    resources :words
    resources :users
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :words, only: :index
  resources :categories, only: :index do
    resources :lessons, only: [:new, :create, :show]
  end
  get 'lesson_learned' => 'lessons#index'
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many   :answers, dependent: :destroy

  validates  :body, presence: true, uniqueness: true
  validates  :category_id, presence: true
  validate   :check_status

  accepts_nested_attributes_for :answers, allow_destroy: true

  scope :learned, ->user {where("id IN (SELECT word_id FROM results
    WHERE lesson_id IN (SELECT id FROM lessons WHERE user_id = '#{user.id}'))")}

  scope :notlearn, ->user {where("id NOT IN (SELECT word_id FROM results
    WHERE lesson_id IN (SELECT id FROM lessons WHERE user_id = '#{user.id}'))")}

  scope :words_category, ->category_id {where category_id: category_id if category_id.present?}
  
  scope :random_words, ->user {Word.notlearn(user).order("random()").limit(20)}
  
  private

  def check_status
    if answers.length < 2
      errors.add :base, "Minimum 2 characters"
    elsif answers.select{|answer| answer.status}.count == 0  
      errors.add :base, "Please select one correct answer"
    elsif answers.select{|answer| answer.status}.count > 1 
      errors.add :base, "Only one correct answer is selected"
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :login_redirect_admin
  
  def index   
    @words = Word.paginate page: params[:page], per_page: 15
  end

  def new
    @word = Word.new
    4.times{@word.answers.build}
  end

  def edit
    @word = Word.find params[:id]
  end

  def create
    @word = Word.new word_params
    if @word.save
      redirect_to admin_words_path
    else
      render "new"
    end
  end

  def update
    @word = Word.find params[:id]

    if @word.update_attributes word_params
      flash[:success] = "Update question successfull"
      redirect_to edit_admin_word_path params[:id]
    else
      render "edit"
    end
  end

  def destroy
    Word.find(params[:id]).destroy
    redirect_to admin_words_path
  end

  private
  
  def word_params
    params.require(:word).permit :body, :category_id,
      answers_attributes: [:id, :body, :status, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all
    
    if %w(learned notlearn).include? params[:status]
      @words = Word.words_category(params[:category_id])
        .send(params[:status], current_user)
        .paginate page: params[:page], per_page: 10
    else
      @words = Word.words_category(params[:category_id])
        .paginate page: params[:page], per_page: 10
    end
  end
end

app/views/admin/words/_answer_field.html.erb
<div class="form-group">
  <%= builder.label "Answer #{builder.options[:child_index]+1}",
        class: "label_answer" %>
  <span class="pull-right">Is true 
    <%= builder.check_box :status, class: "answer_radio" %>
  </span>
  <div class="input-group">
    <%= builder.text_area :body, class: "form-control" %>
    <%= link_to "#", class: "input-group-addon delete_ans",
          id: builder.index do %>
      <i class="glyphicon glyphicon-remove"></i>
    <% end %>
  </div>
</div>
<%= builder.hidden_field(:_destroy) %>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word]  do |f| %>
  <%= render "shared/error", object: f.object %>
  <div class="form-group">
    <%= f.label :"Word Content" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Exam list" %>
    <%= select("word", "category_id", Category.all.collect{|x| [x.name, x.id]},
        {include_blank: true, selected: @word.category_id},
        class: "form-control")
    %>
  </div>

  <div id="answer">
    <%= f.fields_for :answers do |builder| %>
      <%= render "answer_field", builder: builder %>
    <% end %>
  </div>

  <div class="form-group">
    <%= link_to "Back", admin_words_path, class: "btn btn-danger pull-right" %>
    <%= f.submit "Save", class: "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/admin/words/edit.html.erb
<h1>Update Word Page</h1>
<%= render "form" %>

app/views/admin/words/index.html.erb
<h1>List Word Page</h1>
<p align="right">
  <%= link_to "Word new", new_admin_word_path, class: "btn btn-primary" %>
</p>
<table class="table table-bordered" align="center">
  <thead>
    <tr>
      <th width="50">ID</th>
      <th>Word content</th>
      <th width="60">Edit</th>
      <th width="60">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @words.each do |word| %>
      <tr>
      <td><%= word.id %></td>
      <td><%= word.body %></td>
      <td><%= link_to "Edit", edit_admin_word_path(word) %></td>
      <td><%= link_to "Delete", admin_word_path(word),  method: :delete, data: {confirm: "You sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/admin/words/new.html.erb
<h1>Create Word Page</h1>
<%= render "form" %>