config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :users do
    resources :followers, only: :index
    resources :followings, only: :index
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get  'signup' => 'users#new'
  delete 'logout' => 'sessions#destroy'

  namespace :admin do
    root 'dashbroads#home'
    resources :categories
    resources :words
    resources :users
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :words, only: :index
  resources :categories, only: :index do
    resources :lessons, only: [:new, :create, :show]
  end
  get 'lesson_learned' => 'lessons#index'
end

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_show_follow.html.erb
<% provide(:title, @title) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= image_tag @user.avatar.url, width: "100" if @user.avatar %>
      <p><b><%= @user.fullname %><b></p>
      <span><%= link_to "view my profile", @user %></span>
    </section>
    <section class="stats" style="padding-left: 70px;">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>

app/views/shared/_show_user.html.erb
<div class="row">
  <div class="col-md-3">
    <p align="center">
      <%= image_tag @user.avatar.url, width: "100" if @user.avatar %>
      <div style="text-align:center;"><%= @user.fullname %></div>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </p>
  </div>
  <div class="col-md-9">
    <%= render 'users/follow_form' if logged_in? %>
    <h1 align="left">
      <%= link_to words_path do %>
        <span class="label label-default">Words</span>
      <% end %>
      <%= link_to categories_path, class: "lesson" do %>
        <span class="label label-default">Lesson</span>
      <% end %>
    </h1>
    <br/>
    <h3>Activities<hr/></h3>
      <ul class="lesson-categories">
        <%= render @activities %>
      </ul>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to user_followings_path(@user) do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  <% end %>
  <%= link_to user_followers_path(@user) do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  <% end %>
</div>